### PR TITLE
Integrated Travis with flake8 and Remove unused packages #29

### PR DESCRIPTION
**Pull request by ankitjain28may**
Removed unused packages used in the project and the integration of flake8 with travis-ci for checking the code quality of the code in the reference of my issue opened #29

### CODE REVIEW

**Comment by mariobehling** [comment]
@ankitjain28may Thank you. Please help to make it easier for reviewers and open issues before making pull requests. Then match the pull request with the issue in the description and provide details about the pull request. Cheers.

**Comment by ankitjain28may** [comment]
I hve opened issues regarding unused packages and flake8 integration @mariobehling

**Comment by mariobehling** [comment]
Please mention in the description of the pull request which issues you are solving with this pull request.

**Comment by ankitjain28may** [comment]
@mariobehling I have added the description in reference to my issue #29

**Comment by ankitjain28may** [comment]
@rhemon yes, You are right and if you have integrated coala why should the code still have so many linting errors and it is not integrated with travis to check the erros during pull requests and push. I will change this pr and remove the unused packages and later tryto integrate coala with travis

**Comment by rhemon** [comment]
yeah earlier PycodestyleBear and pyflakesbear were not added and so linting errors for those weren't fixed, but now with your previous PR that is mostly fixed except the part of removing unused packages (which you did here). 
so yeah it will be good if you integerate coala in travis instead of running flakes. also make sure to update the .coafile. maybe you want to close this and have a new PR with the new commit? or you can also amend the previous ones whichever is suitable for you.

**Comment by ankitjain28may** [comment]
I will make a new pr.

**Pull request closed without merging**
