### PR TITLE
test added for duckduckgo and askcom

### PR DESCRIPTION
**Pull request by In-vincible**

### CODE REVIEW

**Comment by In-vincible** [comment]
Now we can discuss the tests for generateFeed function and xml response testing.

**Comment by rhemon** [comment]
for generateFeed, to start, you can test the printed output (make sure to have to test it for each search engine)
and for xml response testing also, first do a search on your own and store the xml result (you can do it as a file or as a string variable) and then match the output you receive through the request, you might have to do some changes and use RegExp so that in case the order changes, as long as the result is valid, it should pass.

**Comment by jayanthchandra** [comment]
@In-vincible , If you need help in XML testing i could provide a abstract methods for one search engine and i hope you could continue from there.

**Comment by In-vincible** [comment]
@jayanthchandra yeah that would be great!

**Comment by jayanthchandra** [comment]
@In-vincible  I would do it , after this PR merge

**Comment by mariobehling** [comment]
@In-vincible Thank you. Unfortunately there are merge conflicts because of the previous merge. Please help to solve them.

Also, please help to make it easier for reviewers and always open an issue first, then match the issue and pull request. While you might think this could sometimes be too much for small things, it helps us a lot to keep track of projects and understand previous changes. It also helps to avoid that two people work on the same thing. 

Thanks a lot! Keep it up!

**Comment by rhemon** [comment]
according to me changes here are fine presently 
however there is a lot more left to test like xml testing and generateFeed testing for which I mentioned that first just test the printed outputs and to have it for every search engine option
as of now I guess once conflicts are resolved we can merge this and afterwards we will have a new PR adding other necessary parts. 
also we need to make sure coverage is only for rss-generator.py

**Comment by In-vincible** [comment]
@rhemon I have added the issue for xml testing, I will resolve conflicts than we can merege this PR, after that we can continue with XML testing .

**Pull request merged**
