### PR TITLE
 Remove Flake8-errors

### PR DESCRIPTION
**Pull request by ankitjain28may**
Remove all the flake8 errors.
1- Module `import requests` is not being used in the project.
2- Module `import sys` is not being used in the project.

### CODE REVIEW

**Comment by ankitjain28may** [comment]
@rhemon Please check it out

**Comment by ankitjain28may** [comment]
@mariobehling  Please check it out

**Comment by rhemon** [comment]
changes LGTM. @ankitjain28may  please resolve the conflict.

**Comment by ankitjain28may** [comment]
@rhemon  The conflict are resolved.

**Pull request merged**
