### PR TITLE
Add RSS Generator

### PR DESCRIPTION
**Pull request by jarifibrahim**
Resolves https://github.com/fossasia/labs.fossasia.org/issues/163

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Could you document how it works please and showcase it on a server?

**Comment by Orbiter** [comment]
Hey I just tested this code and it works great!

**Comment by Orbiter** [comment]
thank you!

**Comment by mariobehling** [comment]
@jarifibrahim Please add info about the libraries used to the Readme.md if possible as well. If you like, feel free to take up the follow up task: https://github.com/fossasia/labs.fossasia.org/issues/164 Cheers.

**Comment by jarifibrahim** [comment]
@mariobehling Short description about each of the requirements?

**Comment by mariobehling** [comment]
@jarifibrahim I am mainly referring to the setup info and please provide info, which components are included e.g. Beautiful soup and a link to the website

**Comment by jarifibrahim** [comment]
@mariobehling Every requirement mentioned in README.md file is linked to its official website. Like [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) and [FeedGen](https://github.com/lkiesow/python-feedgen).

**Pull request merged**
